language: python
matrix:
    exclude:
        - python: "3.3"
          env: DJANGO_VERSION=1.4.9
python:
  - "2.7"
  - "3.3"
env:
    - DJANGO_VERSION=1.4.9
    - DJANGO_VERSION=1.5.5
install:
    - pip install .
    - pip install -q nose django-nose Django==$DJANGO_VERSION

script: ./runtests.py
