language: python
python:
  - "2.7"
  - "3.4"
env:
    - DJANGO="Django>=1.6,<1.7" SOUTH='https://bitbucket.org/andrewgodwin/south/get/default.zip'
    - DJANGO='https://github.com/django/django/archive/1.7c2.zip' SOUTH=''
install:
    - pip install -U mock $DJANGO $SOUTH
    - pip install .

script: ./runtests.py
