# Generated by Django 2.0.1 on 2018-02-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_fsm_log', '0002_auto_20151207_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statelog',
            name='object_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
